services:
  ui:
    container_name: inethi-monitoring-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring-ui.rule=Host(`${TRAEFIK_HOST:-monitoring.inethilocal.net}`)"
      - "traefik.http.routers.monitoring-ui.entrypoints=${TRAEFIK_ENTRYPOINTS:-websecure}"

networks:
  default:
    external: true
    name: "${TRAEFIK_NETWORK_BRIDGE:-inethi-bridge-traefik}"
